# Generated by Django 5.1.5 on 2025-02-05 16:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст новости'),
        ),
    ]
