# Generated by Django 5.1.5 on 2025-02-05 17:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_news_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Содержание новости'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
